general {
    lock_cmd = qs -c lock ipc call lock lock
    before_sleep_cmd = qs -c lock ipc call lock lock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 300
    on-timeout = qs -c lock ipc call lock lock && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' && systemctl suspend
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}