hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/cliphist-watch.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/wallpaper.sh init")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/pill-daemon.sh")
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/lock-daemon.sh")
    hl.exec_cmd("obs --startreplaybuffer --disable-shutdown-check")
    -- hl.exec_cmd("systemctl --user enable opentabletdriver.service --now")
    hl.exec_cmd("hypridle & me.timschneeberger.jdsp4linux -t")
end)
